{
 "title": "Energie",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Verbrauch Wärmepumpe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\nmax(\"+A\") - min(\"+A\") as \"Energie\"\nFROM \"ElectricityMeter1\"\nWHERE time >= 1744638835995 / 1000 and time < 1745243635995 / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "rawQueryText": "SELECT time,\nmax(\"+A\") - min(\"+A\") as \"Energie\"\nFROM \"ElectricityMeter1\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wechselrichter Ertrag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\nmax(\"CH0 DC E day\" + \"CH1 DC E day\") as \"Energie\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "rawQueryText": "SELECT time,\nmax(\"CH0 DC E day\" + \"CH1 DC E day\") as \"Energie\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\nmax(\"CH0 DC E day\") as \"Energie Modul 1\"\nFROM \"Inverter\"\nWHERE time >= 1745221829220 / 1000 and time < 1745243429220 / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "rawQueryText": "SELECT time,\nmax(\"CH0 DC E day\") as \"Energie Modul 1\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\nmax(\"CH1 DC E day\") as \"Energie Modul 2\"\nFROM \"Inverter\"\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "rawQueryText": "SELECT time,\nmax(\"CH1 DC E day\") as \"Energie Modul 2\"\nFROM \"Inverter\"\nGROUP BY date(time, \"unixepoch\")\nORDER BY time\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Verbrauch Haus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time,\nmax(\"+A\") - min(\"+A\") as \"Energie\"\nFROM \"ElectricityMeter0\"\nWHERE time >= 1744638835995 / 1000 and time < 1745243635995 / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "rawQueryText": "SELECT time,\nmax(\"+A\") - min(\"+A\") as \"Energie\"\nFROM \"ElectricityMeter0\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Einspeisung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time,\nmax(\"-A\") - min(\"-A\") as \"Energie\"\nFROM \"ElectricityMeter0\"\nWHERE time >= 1744640004969 / 1000 and time < 1745244804969 / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "rawQueryText": "SELECT time,\nmax(\"-A\") - min(\"-A\") as \"Energie\"\nFROM \"ElectricityMeter0\"\nWHERE time >= $__from / 1000 and time < $__to / 1000\nGROUP BY date(time, \"unixepoch\")\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}