{
 "title": "Wechselrichter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Leistung Wechselrichter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\n\"AC P\" as \"AC\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT time,\n\"AC P\" as \"AC\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\n\"CH0 DC P\" as \"Modul 1\"\nFROM \"Inverter\"\nWHERE time >= 1745152239917 / 1000 and time < 1745155839917 / 1000",
     "rawQueryText": "SELECT time,\n\"CH0 DC P\" as \"Modul 1\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\n\"CH1 DC P\" as \"Modul 2\"\nFROM \"Inverter\"\nWHERE time >= 1745152239917 / 1000 and time < 1745155839917 / 1000",
     "rawQueryText": "SELECT time,\n\"CH1 DC P\" as \"Modul 2\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperatur und Netzspannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\n\"T\"\nFROM \"Inverter\"\nWHERE time >= 1745313532715 / 1000 and time < 1745356732715 / 1000",
     "rawQueryText": "SELECT time,\n\"T\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\n\"AC V\"\nFROM \"Inverter\"\nWHERE time >= 1745313532715 / 1000 and time < 1745356732715 / 1000",
     "rawQueryText": "SELECT time,\n\"AC V\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Modul 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time,\n\"CH0 DC V\" as \"Spannung\",\n\"CH0 DC I\" as \"Strom\",\n\"CH0 DC P\" as \"Leistung\",\n\"CH0 DC E day\" as \"Energie Tag\",\n\"CH0 DC E total\" as \"Energie gesamt\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT time,\n\"CH0 DC V\" as \"Spannung\",\n\"CH0 DC I\" as \"Strom\",\n\"CH0 DC P\" as \"Leistung\",\n\"CH0 DC E day\" as \"Energie Tag\",\n\"CH0 DC E total\" as \"Energie gesamt\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Modul 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time,\n\"CH1 DC V\" as \"Spannung\",\n\"CH1 DC I\" as \"Strom\",\n\"CH1 DC P\" as \"Leistung\",\n\"CH1 DC E day\" as \"Energie Tag\",\n\"CH1 DC E total\" as \"Energie gesamt\"\nFROM \"Inverter\"\nWHERE time >= 1745337238901 / 1000 and time < 1745358838901 / 1000",
     "rawQueryText": "SELECT time,\n\"CH1 DC V\" as \"Spannung\",\n\"CH1 DC I\" as \"Strom\",\n\"CH1 DC P\" as \"Leistung\",\n\"CH1 DC E day\" as \"Energie Tag\",\n\"CH1 DC E total\" as \"Energie gesamt\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "AC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time,\n\"CH0 DC E day\" + \"CH1 DC E day\" as \"Energie Tag\",\n\"CH0 DC E total\" + \"CH1 DC E total\" as \"Energie gesamt\",\n\"AC I\" as \"Strom\",\n\"AC F\" as \"Frequenz\",\n\"AC Q\" as \"Blindleistung\",\n\"AC PF\" as \"Power factor\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT time,\n\"CH0 DC E day\" + \"CH1 DC E day\" as \"Energie Tag\",\n\"CH0 DC E total\" + \"CH1 DC E total\" as \"Energie gesamt\",\n\"AC I\" as \"Strom\",\n\"AC F\" as \"Frequenz\",\n\"AC Q\" as \"Blindleistung\",\n\"AC PF\" as \"Power factor\"\nFROM \"Inverter\"\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}