{
 "title": "Übersicht",
 "time": { "from": "2025-04-21T09:15:11.389Z", "to": "2025-04-21T10:55:35.051Z" },
 "panels": [
  {
   "title": "Leistung Haus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\n\"P\"\nFROM ElectricityMeter0\nWHERE time >= $__from / 1000 and time < $__to / 1000\n\n",
     "rawQueryText": "SELECT time,\n\"P\"\nFROM ElectricityMeter0\nWHERE time >= $__from / 1000 and time < $__to / 1000\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Leistung Wärmepumpe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time,\n\"P\"\nfrom ElectricityMeter1\nWHERE time >= 1745128519138 / 1000 and time < 1745150119138 / 1000",
     "rawQueryText": "SELECT time,\n\"P\"\nfrom ElectricityMeter1\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Leistung Wechselrichter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time,\n\"AC P\" as \"AC\"\nFROM Inverter\nWHERE time >= 1745128519138 / 1000 and time < 1745150119138 / 1000\n\n",
     "rawQueryText": "SELECT time,\n\"AC P\" as \"AC\"\nFROM Inverter\nWHERE time >= $__from / 1000 and time < $__to / 1000\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\n\"CH0 DC P\" as \"Modul 1\"\nFROM Inverter\nWHERE time >= 1745128519138 / 1000 and time < 1745150119138 / 1000\n\n",
     "rawQueryText": "SELECT time,\n\"CH0 DC P\" as \"Modul 1\"\nFROM Inverter\nWHERE time >= $__from / 1000 and time < $__to / 1000\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time,\n\"CH1 DC P\" as \"Modul 2\"\nFROM Inverter\nWHERE time >= $__from / 1000 and time < $__to / 1000\n",
     "rawQueryText": "SELECT time,\n\"CH1 DC P\" as \"Modul 2\"\nFROM Inverter\nWHERE time >= $__from / 1000 and time < $__to / 1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Einspeisung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time,\niif(\"P\" < 0, -\"P\", 0) as \"P out\"\nFROM ElectricityMeter0\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT time,\niif(\"P\" < 0, -\"P\", 0) as \"P out\"\nFROM ElectricityMeter0\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}